#pragma once

#include "sep/Rhine.h"
#include "sep/Pat.h"
#include "sep/MadMax.h"

extern RHN_TEXTURE TEXTURE_MAINMENU;
extern RHN_TEXTURE TEXTURE_WALL;
extern RHN_TEXTURE TEXTURE_WALL_CORNER_IN;
extern RHN_TEXTURE TEXTURE_WALL_CORNER_OUT;
extern RHN_TEXTURE TEXTURE_MINI_MAP_FRAME;
extern RHN_TEXTURE TEXTURE_FLOOR;
extern RHN_TEXTURE TEXTURE_PLAYER;
extern RHN_TEXTURE TEXTURE_GHOST;
extern RHN_TEXTURE TEXTURE_CURSOR;
extern RHN_TEXTURE TEXTURE_CROSSHAIR;
extern RHN_TEXTURE TEXTURE_FONT_GEMINI_TYPE;
extern RHN_TEXTURE TEXTURE_GAM_DETECTOR;
extern RHN_TEXTURE TEXTURE_GAM_DETECTOR_ON;
extern RHN_TEXTURE FLAGS_UK;
extern RHN_TEXTURE FLAGS_NL;
extern RHN_TEXTURE FLAGS_DE;
extern MDMX_SOUND SOUND_GAM_IDLE;
extern MDMX_SOUND SOUND_GAM_CLOSE;
extern MDMX_SOUND SOUND_SHOOT;
extern MDMX_SOUND SOUND_DEV_LOAD;


extern const char* CONFIG_FONT_GEMINI_TYPE;
extern const char* LOCALIZATIONS[3];



RHN_TEXTURE GAME_GetRhineTexture(PAT_ASSETPACK* pack,const char* key);
MDMX_SOUND GAME_GetMDMXSound(PAT_ASSETPACK* pack, const char* key);
void ASSETS_LOAD();
